# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту consthomespb@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -consthomespb@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
jdk: -openjdk11

services:
  - postgresql

before_install:
  - psql -c "ALTER USER postgres WITH PASSWORD 'Qqqqqqqq1';" -U postgres
  - psql -c 'create database tracker;' -U postgres
